#pragma once

#define LED_PIN 7

#define I2C_SDA 5
#define I2C_SCL 6

#define BUTTON_PIN 0
#define BUTTON_NEED_PULLUP
#define ALT_BUTTON_PIN 38
#define ALT_BUTTON_ACTIVE_LOW true
#define ALT_BUTTON_ACTIVE_PULLUP true
#define BUTTON_CLICK_MS 400

#define BATTERY_PIN 4
#define ADC_CHANNEL ADC_CHANNEL_3
#define ADC_ATTENUATION ADC_ATTEN_DB_2_5
#define ADC_MULTIPLIER 4.966

#define USE_SX1262
#define LORA_SCK 9
#define LORA_MISO 10
#define LORA_MOSI 11
#define LORA_CS 12
#define LORA_RESET 13
#define LORA_DIO1 14
#define LORA_BUSY 3
#define LORA_RXEN 46
#define LORA_DIO0 RADIOLIB_NC
#define LORA_DIO3 RADIOLIB_NC

#define SX126X_CS LORA_CS
#define SX126X_DIO1 LORA_DIO1
#define SX126X_BUSY LORA_BUSY
#define SX126X_RESET LORA_RESET
#define SX126X_RXEN LORA_RXEN
#define SX126X_TXEN RADIOLIB_NC
#define SX126X_DIO2_AS_RF_SWITCH

#define HAS_NEOPIXEL
#define NEOPIXEL_COUNT 8
#define NEOPIXEL_DATA 8
#define NEOPIXEL_TYPE (NEO_GRB + NEO_KHZ800)
